
language: python
branches:
  except:
    - gh-pages
before_install:
  - sudo apt-get -qq update
install:
  - python -m pip install -U pip setuptools
  - pip install -U six
  - pip install codecov
  - pip install tox
matrix:
  include:
    - python: 2.7
      env:
        - TOXENV=py27
    - python: 3.4
      env:
        - TOXENV=py34
    - python: 3.5
      env:
        - TOXENV=py35
    - python: 3.6
      env:
        - TOXENV=py36
    - python: 3.7
      env:
        - TOXENV=py37
script:
  - tox
after_success:
  - codecov
