
language: python
branches:
  except:
    - gh-pages
before_install:
  - sudo apt-get -qq update
install:
  - python -m pip install -U pip setuptools
  - pip install -U six
  - pip install codecov
  - pip install tox
matrix:
  include:
    - python: 2.7
      env:
        - TOXENV=py27-sync
    - python: 2.7
      env:
        - TOXENV=py27-nosync
    - python: 3.5
      env:
        - TOXENV=py35-sync
    - python: 3.5
      env:
        - TOXENV=py35-nosync
    - python: 3.6
      env:
        - TOXENV=py36-sync
    - python: 3.6
      env:
        - TOXENV=py36-nosync
script:
  - tox
after_success:
  - codecov
